services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    branch: main
    autoscale:
      minInstances: 1
      maxInstances: 3
    envVars:
      - key: NODE_ENV
        value: production
